module.exports ={
    //Home
    GET_CATEGORY_LIST:'GET_CATEGORY_LIST',
    GET_DISHES: 'GET_DISHES',
    GET_SUBMENU:'GET_SUBMENU',
    UPDATE_SELECTED_CATEGORY:'UPDATE_SELECTED_CATEGORY',
    GET_SELECTED_CATEGORY:'GET_SELECTED_CATEGORY',
};